### ISSUE TITLE
Compatibility with Yoast SEO: meta name="robots"

### ISSUE THREAD

**Issue by peter-fb** [brainstormforce/unlist-posts#33]
I'm using Yoast SEO.

If you use both plugins, there will be 2 entries with almost the same settings in your page source:

Yoast SEO:
`<meta name="robots" content="noindex,follow"/>`

Unlist Posts & Pages:
`<meta name='robots' content='noindex,follow' />`

-> I have configured Yoast SEO to also do the same "noindex,follow" thing. If you don't do that, you will have conflicting rules.

In any case, it's not good if you have two rules for meta name="robots", even if they're (almost) the same.

**Comment by Nikschavan** [comment]
Hi @peter-fb - We are working on fixing this, With WordPress 5.7 (#52) and new WordPress robots tags filters the meta tag can have conflicting meta tags = eg - `<meta name='robots' content='index, noindex, follow' />`

We will be increasing the priority of our filter so that if the post is unlisted will only add `noindex` and not add both `index` and `noindex` even if you have set it from Yoast SEO.

**Comment by Nikschavan** [comment]
Closing this as this has been fixed and released on W.org
