### ISSUE TITLE
Show in WordPress API

### ISSUE THREAD

**Issue by Jonofat** [brainstormforce/unlist-posts#74]
Hi, I want to hide the posts on the frontend which is working but I don't want to hide them in the WordPress API. I created a custom endpoint and trying to use ` 'suppress_filters' => true,` but it still doesn't show the posts. 

```
    $args = array(
        'suppress_filters' => true,
        'post_type' => 'my-cpt',
        'posts_per_page' => -1,
        'tax_query' => array(
        array(
            'taxonomy' => 'my-tax',
            'field'    => 'id',
            'terms'    => '6',
        ),
    ),
    );
```

**Comment by Nikschavan** [comment]
The unlisted posts are removed using the filter [`posts_where`](https://github.com/brainstormforce/unlist-posts/blob/e1150304159578813ea2a3407245ec643cba9f9b/class-unlist-posts.php#L61) so that is not affected by the `suppress_filters` which only suppresses filters inside `WP_Query`.

What you can do is, remove the filter I mentioned above before doing your query and then re-add it.

For eg - 

```PHP
$unlist_posts = Unlist_Posts::instance();
remove_filter( 'posts_where', array( $unlist_posts, 'where_clause' ), 20, 2 );

// Your WP_Query.

add_filter( 'posts_where', array( $unlist_posts, 'where_clause' ), 20, 2 );
```

So this will run the query without this filter from this plugin and hence the unlisted posts should be displayed in your query.

**Comment by Jonofat** [comment]
Thanks so much for this, it works nicely. Very much appreciated, thanks again!
